// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj9MEbJUuu64Nf6NKtwo8_WS-PgII8Rx8',
    appId: '1:200720307380:web:7c525c4e4b06a28fdf33e1',
    messagingSenderId: '200720307380',
    projectId: 'pinterest-clone-16316',
    authDomain: 'pinterest-clone-16316.firebaseapp.com',
    storageBucket: 'pinterest-clone-16316.firebasestorage.app',
    measurementId: 'G-CPWQ45W6Z7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOIiGjq27nn5wDx8yhjWbqgYRW4Kb4NPA',
    appId: '1:200720307380:android:6643a3cf2fd08743df33e1',
    messagingSenderId: '200720307380',
    projectId: 'pinterest-clone-16316',
    storageBucket: 'pinterest-clone-16316.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-7QoUWQkKLEVc8InLln6CJbnMqhYFDMY',
    appId: '1:200720307380:ios:f0d62d0cb72cc4ebdf33e1',
    messagingSenderId: '200720307380',
    projectId: 'pinterest-clone-16316',
    storageBucket: 'pinterest-clone-16316.firebasestorage.app',
    iosBundleId: 'com.example.pinterestClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-7QoUWQkKLEVc8InLln6CJbnMqhYFDMY',
    appId: '1:200720307380:ios:f0d62d0cb72cc4ebdf33e1',
    messagingSenderId: '200720307380',
    projectId: 'pinterest-clone-16316',
    storageBucket: 'pinterest-clone-16316.firebasestorage.app',
    iosBundleId: 'com.example.pinterestClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj9MEbJUuu64Nf6NKtwo8_WS-PgII8Rx8',
    appId: '1:200720307380:web:c74196989fa903e4df33e1',
    messagingSenderId: '200720307380',
    projectId: 'pinterest-clone-16316',
    authDomain: 'pinterest-clone-16316.firebaseapp.com',
    storageBucket: 'pinterest-clone-16316.firebasestorage.app',
    measurementId: 'G-0SJBCCDX6B',
  );
}
